name: Linter

on:
  push:
    branches:
      - build2

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn clean install
      - name: Run Junit Tests
        run: mvn test
      - name: Check JavaDoc
        run: mvn checkstyle:checkstyle
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

